#!/bin/bash

RE_VIRTHOSTROOTURL="(([a-zA-Z0-9\._-]+\.[a-zA-Z]{2,6})|([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}))(:[0-9]{1,4})*(/[a-zA-Z0-9\&%_\./-~-]*)?"

RE_CONTPORT="^[1][0-9]{3}$|^[2-9][0-9]{3}$|^[1-3][0-9]{4}$|^4[0-9][0-1][0-5][0-1]$"

if [ "$#" = "4"  ]; then
  if [[ "$2" =~ $RE_VIRTHOSTROOTURL ]];then
    if [[ "$3" =~ $RE_CONTPORT ]];then
    :
    else
      echo "Invalid arguments"
      echo $1 $2 $3 $4
      echo "[example]: setmup domainName url port"
      echo "[example] domainName : example"
      echo "[example] url : wiki.maodou.io or 192.168.1.1"
      echo "[example] port  goes from 1024 to 49151"
      exit -1
    fi
  fi
  if [  -f "$4" ]; then
    echo $1 $2 $3 $4
    sed -i '/\"virtual_host\"/s/\:.*/\: \"'"$2"'\",/g' $4
    sed -i '/\"ROOT_URL\"/s/\:.*/\: \"http\:\/\/'"$2"'\",/g' $4
    sed -i '/\"appName\"/s/\:.*/\: \"'"$1"'\",/g' $4
    sed -i '/\"meteor_container_port\"/s/\:.*/\: \"'"$3"'\",/g' $4
  else
    echo "$4 is not exist"
    exit -1
  fi
else if [ "$#"="1" -a "$1"="--help" ]; then
       echo "[use it like this]: #./setmup domainName url port mup.json"
       echo "[example]: setmup example example.maodou.io 8000 /tmp/maodou-meteor/mup.json"
     else
       echo "[Syntax Error]: You typed the wrong number of arguments to that command."
     fi
fi
